package projecttwo

import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions
import org.apache.spark.sql.DataFrameReader
import org.apache.http.impl.client.HttpClients
import org.apache.http.client.config.RequestConfig
import org.apache.http.client.config.CookieSpecs
import org.apache.http.client.utils.URIBuilder
import org.apache.http.client.methods.HttpGet
import java.io.BufferedReader
import java.io.InputStreamReader
import java.io.PrintWriter
import java.nio.file.Files
import java.nio.file.Paths
import scala.concurrent.Future

object TrackPositiveTweetLocaton {
    def demoPositiveTweetLocation (spark: SparkSession)= {
        helloTweetStream(spark)
    }

    def helloTweetStream(spark: SparkSession): Unit = {
    import spark.implicits._

    //grab a bearer token from the environment
    //never hardcode your tokens (never just put them as a string in your code)
    val bearerToken = System.getenv(("TWITTER_BEARER_TOKEN"))

    //writes all the tweets from twitter's stream into a directory
    // by default hits the sampled stream and uses "twitterstream" as the directory
    // We'll run it in the background using a Future:
    // We're not saving a reference to this future or providing a callback function
    // we just start it running in the background and forget about it.
    import scala.concurrent.ExecutionContext.Implicits.global
    Future {
      TrackTimeLocation.tweetStreamToDir(bearerToken, queryString = "?tweet.fields=geo,created_at&expansions=geo.place_id")
    }

    //Here we're just going to wait until a file appears in our twitterstream directory
    // or until some reasonable amount of time has passed (30s)
    var start = System.currentTimeMillis()
    var filesFoundInDir = false
    while(!filesFoundInDir && (System.currentTimeMillis()-start) < 30000) {
      filesFoundInDir = Files.list(Paths.get("twitterstream1")).findFirst().isPresent()
      Thread.sleep(500)
    }
    if(!filesFoundInDir) {
      println("Error: Unable to populate tweetstream after 30 seconds.  Exiting..")
      System.exit(1)
    }

    //We're going to start with a static DF
    // both to demo it, and to infer the schema
    // streaming dataframes can't infer schema
    val staticDf = spark.read.json("twitterstream1")

    staticDf.printSchema()

    //streamDf is a stream, using *Structured Streaming*
    val streamDf1 = spark.readStream.schema(staticDf.schema).json("twitterstream1")


    streamDf1
        .filter(!functions.isnull($"includes.places"))
      .select(($"data.text").as("Text"),functions.hour($"data.created_at").as("Time_In_EST"))
      .where(
        ($"data.text".like("%absolutely%"))
        or($"data.text".like("%accepted%"))
        or($"data.text".like("%acclaimed%"))
        or($"data.text".like("%accomplish%"))
        or($"data.text".like("%accomplishment%"))
        or($"data.text".like("%achievement%"))
        or($"data.text".like("%action%"))
        or($"data.text".like("%active%"))
        or($"data.text".like("%admire%"))
        or($"data.text".like("%adorable%"))
        or($"data.text".like("%adventure%"))
        or($"data.text".like("%affirmative%"))
        or($"data.text".like("%affluent%"))
        or($"data.text".like("%agree%"))
        or($"data.text".like("%amazing%"))
        or($"data.text".like("%angelic%"))
        or($"data.text".like("%appealing%"))
        or($"data.text".like("%approve%"))
        or($"data.text".like("%aptitude%"))
        or($"data.text".like("%attractive%"))
        or($"data.text".like("%awesome%"))
        or($"data.text".like("%beaming%"))
        or($"data.text".like("%beautiful%"))
        or($"data.text".like("%believe%"))
        or($"data.text".like("%beneficial%"))
        or($"data.text".like("%bliss%"))
        or($"data.text".like("%bountiful%"))
        or($"data.text".like("%bounty%"))
        or($"data.text".like("%brave%"))
        or($"data.text".like("%bravo%"))
        or($"data.text".like("%brilliant%"))
        or($"data.text".like("%bubbly%"))
        or($"data.text".like("%calm%"))
        or($"data.text".like("%celebrated%"))
        or($"data.text".like("%certain%"))
        or($"data.text".like("%champ%"))
        or($"data.text".like("%champion%"))
        or($"data.text".like("%charming%"))
        or($"data.text".like("%cheery%"))
        or($"data.text".like("%choice%"))
        or($"data.text".like("%classic%"))
        or($"data.text".like("%clean%"))
        or($"data.text".like("%commend%"))
        or($"data.text".like("%composed%"))
        or($"data.text".like("%congratulation%"))
        or($"data.text".like("%constant%"))
        or($"data.text".like("%cool%"))
        or($"data.text".like("%courageous%"))
        or($"data.text".like("%creative%"))
        or($"data.text".like("%cute%"))
        or($"data.text".like("%dazzling%"))
        or($"data.text".like("%delight%"))
        or($"data.text".like("%distinguished%"))
        or($"data.text".like("%divine%"))
        or($"data.text".like("%earnest%"))
        or($"data.text".like("%easy%"))
        or($"data.text".like("%ecstatic%"))
        or($"data.text".like("%effective%"))
        or($"data.text".like("%effervescent%"))
        or($"data.text".like("%efficient%"))
        or($"data.text".like("%effortless%"))
        or($"data.text".like("%electrifying%"))
        or($"data.text".like("%elegant%"))
        or($"data.text".like("%enchanting%"))
        or($"data.text".like("%encouraging%"))
        or($"data.text".like("%endorsed%"))
        or($"data.text".like("%energetic%"))
        or($"data.text".like("%energized%"))
        or($"data.text".like("%engaging%"))
        or($"data.text".like("%enthusiastic%"))
        or($"data.text".like("%essential%"))
        or($"data.text".like("%esteemed%"))
        or($"data.text".like("%ethical%"))
        or($"data.text".like("%excellent%"))
        or($"data.text".like("%exciting%"))
        or($"data.text".like("%exquisite%"))
        or($"data.text".like("%fabulous%"))
        or($"data.text".like("%fair%"))
        or($"data.text".like("%familiar%"))
        or($"data.text".like("%famous%"))
        or($"data.text".like("%fantastic%"))
        or($"data.text".like("%favorable%"))
        or($"data.text".like("%fetching%"))
        or($"data.text".like("%fine%"))
        or($"data.text".like("%fitting%"))
        or($"data.text".like("%flourishing%"))
        or($"data.text".like("%fortunate%"))
        or($"data.text".like("%free%"))
        or($"data.text".like("%fresh%"))
        or($"data.text".like("%friendly%"))
        or($"data.text".like("%fun%"))
        or($"data.text".like("%funny%"))
        or($"data.text".like("%generous%"))
        or($"data.text".like("%genius%"))
        or($"data.text".like("%genuine%"))
        or($"data.text".like("%giving%"))
        or($"data.text".like("%glamorous%"))
        or($"data.text".like("%glowing%"))
        or($"data.text".like("%good%"))
        or($"data.text".like("%gorgeous%"))
        or($"data.text".like("%graceful%"))
        or($"data.text".like("%great%"))
        or($"data.text".like("%green%"))
        or($"data.text".like("%grin%"))
        or($"data.text".like("%growing%"))
        or($"data.text".like("%handsome%"))
        or($"data.text".like("%happy%"))
        or($"data.text".like("%harmonious%"))
        or($"data.text".like("%healing%"))
        or($"data.text".like("%healthy%"))
        or($"data.text".like("%hearty%"))
        or($"data.text".like("%heavenly%"))
        or($"data.text".like("%honest%"))
        or($"data.text".like("%honorable%"))
        or($"data.text".like("%honored%"))
        or($"data.text".like("%hug%"))
        or($"data.text".like("%lively%"))
        or($"data.text".like("%lovely%"))
        or($"data.text".like("%lucky%"))
        or($"data.text".like("%luminous%"))
        or($"data.text".like("%❤%"))
        or($"data.text".like("%😍%"))
        or($"data.text".like("%💛%"))
        or($"data.text".like("%😊%"))
        or($"data.text".like("%😂%"))
        or($"data.text".like("%😃%"))
        )
      .groupBy("Time_In_EST")
      .count().withColumnRenamed("count","positive_tweet_count")
      .writeStream
      .outputMode("complete")
      .format("console")
      .start()
      .awaitTermination()


      streamDf1
        .filter(functions.isnull($"includes.places"))
      .select(($"data.text").as("Text"),functions.hour($"data.created_at").as("Time_In_EST"))
      .where(
        ($"data.text".like("%absolutely%"))
        or($"data.text".like("%accepted%"))
        or($"data.text".like("%acclaimed%"))
        or($"data.text".like("%accomplish%"))
        or($"data.text".like("%accomplishment%"))
        or($"data.text".like("%achievement%"))
        or($"data.text".like("%action%"))
        or($"data.text".like("%active%"))
        or($"data.text".like("%admire%"))
        or($"data.text".like("%adorable%"))
        or($"data.text".like("%adventure%"))
        or($"data.text".like("%affirmative%"))
        or($"data.text".like("%affluent%"))
        or($"data.text".like("%agree%"))
        or($"data.text".like("%amazing%"))
        or($"data.text".like("%angelic%"))
        or($"data.text".like("%appealing%"))
        or($"data.text".like("%approve%"))
        or($"data.text".like("%aptitude%"))
        or($"data.text".like("%attractive%"))
        or($"data.text".like("%awesome%"))
        or($"data.text".like("%beaming%"))
        or($"data.text".like("%beautiful%"))
        or($"data.text".like("%believe%"))
        or($"data.text".like("%beneficial%"))
        or($"data.text".like("%bliss%"))
        or($"data.text".like("%bountiful%"))
        or($"data.text".like("%bounty%"))
        or($"data.text".like("%brave%"))
        or($"data.text".like("%bravo%"))
        or($"data.text".like("%brilliant%"))
        or($"data.text".like("%bubbly%"))
        or($"data.text".like("%calm%"))
        or($"data.text".like("%celebrated%"))
        or($"data.text".like("%certain%"))
        or($"data.text".like("%champ%"))
        or($"data.text".like("%champion%"))
        or($"data.text".like("%charming%"))
        or($"data.text".like("%cheery%"))
        or($"data.text".like("%choice%"))
        or($"data.text".like("%classic%"))
        or($"data.text".like("%clean%"))
        or($"data.text".like("%commend%"))
        or($"data.text".like("%composed%"))
        or($"data.text".like("%congratulation%"))
        or($"data.text".like("%constant%"))
        or($"data.text".like("%cool%"))
        or($"data.text".like("%courageous%"))
        or($"data.text".like("%creative%"))
        or($"data.text".like("%cute%"))
        or($"data.text".like("%dazzling%"))
        or($"data.text".like("%delight%"))
        or($"data.text".like("%distinguished%"))
        or($"data.text".like("%divine%"))
        or($"data.text".like("%earnest%"))
        or($"data.text".like("%easy%"))
        or($"data.text".like("%ecstatic%"))
        or($"data.text".like("%effective%"))
        or($"data.text".like("%effervescent%"))
        or($"data.text".like("%efficient%"))
        or($"data.text".like("%effortless%"))
        or($"data.text".like("%electrifying%"))
        or($"data.text".like("%elegant%"))
        or($"data.text".like("%enchanting%"))
        or($"data.text".like("%encouraging%"))
        or($"data.text".like("%endorsed%"))
        or($"data.text".like("%energetic%"))
        or($"data.text".like("%energized%"))
        or($"data.text".like("%engaging%"))
        or($"data.text".like("%enthusiastic%"))
        or($"data.text".like("%essential%"))
        or($"data.text".like("%esteemed%"))
        or($"data.text".like("%ethical%"))
        or($"data.text".like("%excellent%"))
        or($"data.text".like("%exciting%"))
        or($"data.text".like("%exquisite%"))
        or($"data.text".like("%fabulous%"))
        or($"data.text".like("%fair%"))
        or($"data.text".like("%familiar%"))
        or($"data.text".like("%famous%"))
        or($"data.text".like("%fantastic%"))
        or($"data.text".like("%favorable%"))
        or($"data.text".like("%fetching%"))
        or($"data.text".like("%fine%"))
        or($"data.text".like("%fitting%"))
        or($"data.text".like("%flourishing%"))
        or($"data.text".like("%fortunate%"))
        or($"data.text".like("%free%"))
        or($"data.text".like("%fresh%"))
        or($"data.text".like("%friendly%"))
        or($"data.text".like("%fun%"))
        or($"data.text".like("%funny%"))
        or($"data.text".like("%generous%"))
        or($"data.text".like("%genius%"))
        or($"data.text".like("%genuine%"))
        or($"data.text".like("%giving%"))
        or($"data.text".like("%glamorous%"))
        or($"data.text".like("%glowing%"))
        or($"data.text".like("%good%"))
        or($"data.text".like("%gorgeous%"))
        or($"data.text".like("%graceful%"))
        or($"data.text".like("%great%"))
        or($"data.text".like("%green%"))
        or($"data.text".like("%grin%"))
        or($"data.text".like("%growing%"))
        or($"data.text".like("%handsome%"))
        or($"data.text".like("%happy%"))
        or($"data.text".like("%harmonious%"))
        or($"data.text".like("%healing%"))
        or($"data.text".like("%healthy%"))
        or($"data.text".like("%hearty%"))
        or($"data.text".like("%heavenly%"))
        or($"data.text".like("%honest%"))
        or($"data.text".like("%honorable%"))
        or($"data.text".like("%honored%"))
        or($"data.text".like("%hug%"))
        or($"data.text".like("%lively%"))
        or($"data.text".like("%lovely%"))
        or($"data.text".like("%lucky%"))
        or($"data.text".like("%luminous%"))
        or($"data.text".like("%❤%"))
        or($"data.text".like("%😍%"))
        or($"data.text".like("%💛%"))
        or($"data.text".like("%😊%"))
        or($"data.text".like("%😂%"))
        or($"data.text".like("%😃%"))
        )
      .groupBy("Time_In_EST")
      .count().withColumnRenamed("count","positive_tweet_count")
      .writeStream
      .outputMode("complete")
      .format("console")
      .start()
      .awaitTermination()


  // streamDf1
  //       .filter(!functions.isnull($"includes.places"))
  //     .select(functions.hour($"data.created_at").as("hour"))
  //     .groupBy("hour")
  //     .count()
  //     .writeStream
  //     .outputMode("complete")
  //     .format("console")
  //     .start()
  //     .awaitTermination()

  }
}